### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by douardda**
This is my branch with various improvements I made to be able to run the code on an esp32s2 (WROVER-I)

This code "works" on this target, but it seems the S2 is too slow (maybe being a single core CPU is not enough here, or it's just a matter of adjusting properly some priority parameters or so).

This is probably not a PR to include as is, but it provides a few git revisions:
-  Make the wifi configurable via menuconfig
- Replace the old version of esp-dsp by current version as a submodule
- Remove ntp related code
- Replace usage of ll dsps_biquad_f32_ae32 by dsps_biquad_f32
- Remove commented/obsolete code
- Add a board definition for soala + pcm5142

Tell me if you want to cherry-pick some of those.

### CODE REVIEW

**Comment by douardda** [comment]
For the record, I've received an esp32 WROVER board ([this one](https://www.aliexpress.com/item/4001049652653.html)) and it works much better than the esp32s2 (no glitch but at startup, I guess something about the convergence time of the opus decoder). The second core might be the winner here, I guess. (I've compiled my branch, aka this PR), with PSRAM and cpus clocked at 240MHz.

Also, as there is no latency control in this version of the code I have something like 200/300ms of delay related to the snapclient running on my android phone and the snapclient driving my main amplifier running on a Linux SBC (an orangepilite).

I may give a try to the ideas provided by @constant-flow in the issue #9

**Comment by jorgenkraghjakobsen** [comment]
Hi David -
I will look in to you code - did not do that jet. 
I added a time stamp to the ring buffer and moved the pace control to the audio backend (dsp_processor) - Here i take a look on the age of the sample chunks before I pass data on to the audio processing / I2S DMA hardware. 
Concept works as expected and I can do advanced APLL time to sync the stream. 
I have added a flow monitor to the front end that will signal backend if the stream times out, has stopped or other events. The backend then know what amount of samples left in the ring buffer and can act on that. The code needs clean up - I have started slow pace. 
Glad to hear you are on the Wrover - did get hands on some s2 and eager to check if float performance has increase - x8 as far as I understood. 
/Jørgen

**Comment by douardda** [comment]
> I added a time stamp to the ring buffer

super cool! I'll try this tonight.

**Comment by douardda** [comment]
Ok I've been able to rebase my branch on master, but jeez your big single commit with many unrelated changes in it does not make the job easy... I need to rework my branch a bit and I'll push it.

Also, it would really be nice to have the merusaudio dedicated code in a hal-compatible component.

**Comment by jorgenkraghjakobsen** [comment]
Nice work on the esp-dsp submodule - It plays nicely here.
I still on my path to do a full snapclient component that will work as an audio source (frontend). 
Now adding pcm and will take a look on you FLAC imp and include that if eacy 
HAL backend is very much needed. /j

**Comment by miLORD1337** [comment]
Very nice, I made Wifi configurable via menuconfig as well, but your is nicer with max. retries. So I guess mine is obsolete now.

Great to still see some progress here!

**Comment by douardda** [comment]
This PR is mostly not ready for merge (in fact I think I'll drop it). Now the esp-dsp PR has been merged, I can easily create new PRs focused on each point I started to address in this PR. Stay tuned!

**Comment by douardda** [comment]
Let me abandon this PR in favor of #17 (plus more to come).

**Pull request closed without merging**
